version: "3"

networks:
  challenge:

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGO_CONNECTION_URL: "mongodb://root:root@mongo:27017/"
      MONGO_DB: "jitterbit-challenge-1"
    networks:
      - challenge
    ports:
      - "6000:6000"
  mongo:
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - challenge
